# Generated by Django 3.2.13 on 2022-06-26 21:35

import apps.courses.models.courses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/example.jpg",
                null=True,
                upload_to=apps.courses.models.courses.get_directory_path,
                verbose_name="Image of course",
            ),
        ),
    ]
