# Generated by Django 3.2.13 on 2022-06-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("READY", "Ready")],
                default="DRAFT",
                max_length=255,
                verbose_name="Status of course",
            ),
        ),
    ]
